import * as cheerio from "cheerio"
import { finding, summarize, sortFindings, detectStack } from "./findings"

// Default titles/descriptions left behind by templates and AI builders.
const TEMPLATE_TITLES = [
  "vite + react", "vite + react + ts", "vite + vue", "vite + vue + ts",
  "vite + svelte", "vite + svelte + ts", "vite + preact", "vite app",
  "react app", "create next app", "next.js", "lovable app",
  "lovable generated project", "v0 app", "my v0 project", "bolt",
  "my app", "my website", "new project", "untitled", "document", "index"
]

const TEMPLATE_DESCRIPTIONS = [
  "generated by create next app",
  "web site created using create-react-app",
  "lovable generated project",
  "created with v0",
  "a new website"
]

const LOCAL_URL = /\b(localhost|127\.0\.0\.1|0\.0\.0\.0)\b/i

/**
 * @param {string} html
 * @param {string} url      final URL after redirects
 * @param {number} status
 * @param {object} extra    { headers, robotsTxt, sitemapFound }
 */
export function runSeoChecks(html, url, status, extra = {}) {
  const { headers = {}, robotsTxt = null, sitemapFound = false } = extra
  const $ = cheerio.load(html)
  const parsedUrl = new URL(url)

  // -----------------------------
  // TITLE TAGS
  // -----------------------------
  const titles = $("title")
    .map((i, el) => $(el).text().trim())
    .get()

  const primaryTitle = titles[0] || ""

  // -----------------------------
  // META DESCRIPTION
  // -----------------------------
  const metaDescription =
    $('meta[name="description"]').attr("content")?.trim() || ""

  // -----------------------------
  // CANONICAL
  // -----------------------------
  const canonical = $('link[rel="canonical"]').attr("href") || ""
  let canonicalResolved = ""
  try {
    canonicalResolved = canonical ? new URL(canonical, url).toString() : ""
  } catch {
    canonicalResolved = ""
  }
  const stripSlash = u => u.replace(/\/$/, "")
  const canonicalMismatch =
    !!canonical && stripSlash(canonicalResolved) !== stripSlash(url)

  // -----------------------------
  // ROBOTS META + HEADER
  // -----------------------------
  const robotsMeta = $('meta[name="robots"]').attr("content") || ""
  const xRobots = String(headers["x-robots-tag"] || "")
  const noindex = /noindex/i.test(robotsMeta) || /noindex/i.test(xRobots)

  // -----------------------------
  // VIEWPORT + LANG + FAVICON
  // -----------------------------
  const viewport = $('meta[name="viewport"]').attr("content") || ""
  const lang = $("html").attr("lang") || ""
  const favicon = $('link[rel~="icon"]').attr("href") || ""

  // -----------------------------
  // HEADINGS
  // -----------------------------
  const h1s = $("h1")
    .map((i, el) => $(el).text().trim())
    .get()

  const headings = []
  $("h1, h2, h3, h4, h5, h6").each((i, el) => {
    headings.push({
      tag: el.tagName.toLowerCase(),
      text: $(el).text().trim()
    })
  })

  // -----------------------------
  // STRUCTURED DATA (before scripts are stripped below)
  // -----------------------------
  const schema = $('script[type="application/ld+json"]')
    .map((i, el) => {
      try {
        return JSON.parse($(el).html())
      } catch {
        return null
      }
    })
    .get()
    .filter(Boolean)

  // -----------------------------
  // WORD COUNT (visible text only)
  // -----------------------------
  const $text = cheerio.load(html)
  $text("script, style, noscript, template, svg").remove()
  const bodyText = $text("body").text().replace(/\s+/g, " ").trim()
  const wordCount = bodyText ? bodyText.split(" ").length : 0

  // Single-page-app shell: empty mount point and (almost) no text.
  const emptyMount = ["#root", "#app", "#__next", "#__nuxt", "#svelte"].some(
    sel => $(sel).length > 0 && $(sel).text().trim() === "" && $(sel).children().length === 0
  )
  const isEmptyShell = wordCount < 50 && (emptyMount || $('script[type="module"]').length > 0)

  // -----------------------------
  // IMAGES
  // -----------------------------
  const images = $("img")
  const imagesMissingAlt = images.filter((i, el) => !$(el).attr("alt")).length

  const mixedContent = images
    .map((i, el) => $(el).attr("src"))
    .get()
    .filter(src => src && src.startsWith("http://"))

  // -----------------------------
  // LINKS
  // -----------------------------
  const internalLinks = []
  const externalLinks = []

  $("a").each((i, el) => {
    const href = $(el).attr("href")
    if (!href || href.startsWith("#") || /^(mailto|tel|javascript):/i.test(href)) return

    let isExternal = false
    try {
      isExternal = new URL(href, url).hostname !== parsedUrl.hostname
    } catch {
      return
    }

    if (isExternal) externalLinks.push(href)
    else internalLinks.push(href)
  })

  // -----------------------------
  // OPEN GRAPH + TWITTER
  // -----------------------------
  const og = {
    title: $('meta[property="og:title"]').attr("content") || "",
    description: $('meta[property="og:description"]').attr("content") || "",
    image: $('meta[property="og:image"]').attr("content") || "",
    url: $('meta[property="og:url"]').attr("content") || ""
  }

  const twitter = {
    card: $('meta[name="twitter:card"]').attr("content") || "",
    title: $('meta[name="twitter:title"]').attr("content") || "",
    description: $('meta[name="twitter:description"]').attr("content") || "",
    image: $('meta[name="twitter:image"]').attr("content") || ""
  }

  // -----------------------------
  // ROBOTS.TXT
  // -----------------------------
  const robotsBlocksAll = robotsTxtBlocksAll(robotsTxt)

  const isHttps = url.startsWith("https://")

  // -----------------------------
  // FINDINGS
  // -----------------------------
  const findings = []
  const passed = []
  const check = (ok, passLabel, f) => (ok ? passed.push(passLabel) : findings.push(f()))

  check(status >= 200 && status < 300, "Page returns a success status", () =>
    finding("status", "high", `Page returned HTTP ${status}`,
      "Search engines only index pages that load successfully. Error or redirect statuses on your main page stop it from ranking.",
      `My page ${url} returns HTTP ${status}. Make it return 200 OK.`))

  check(!noindex, "Page allows search engine indexing", () =>
    finding("noindex", "critical", "Your page tells Google not to index it",
      "A `noindex` robots meta tag or X-Robots-Tag header is set, so the page will never appear in search results. AI builders often leave this on from preview/staging.",
      "Remove the `noindex` robots meta tag / X-Robots-Tag header from production so search engines can index the site.",
      robotsMeta || xRobots))

  check(!robotsBlocksAll, "robots.txt does not block all crawlers", () =>
    finding("robots-block-all", "critical", "robots.txt blocks every search engine",
      "Your robots.txt has `Disallow: /` for all user agents, so crawlers are told to stay away from the whole site.",
      "Update robots.txt so it allows crawling in production (e.g. `User-agent: *` with `Allow: /`) and add a `Sitemap:` line."))

  check(!isEmptyShell, "Page has real content in the HTML", () =>
    finding("empty-shell", "critical", "Search engines see a blank page",
      `The HTML contains only ${wordCount} words of text; the content is drawn by JavaScript after load. Google may index it slowly or incompletely, and social previews, Bing, and AI search crawlers usually see nothing. This is the #1 SEO problem for Vite/React apps built with Lovable, Bolt and similar tools.`,
      "My site is a client-side rendered React (Vite) app, so crawlers see an empty <div id=\"root\">. Add prerendering or server-side rendering so each page's HTML contains its real content, titles and meta tags (e.g. migrate to Next.js, or add a static prerender step for each route)."))

  if (!isEmptyShell) {
    check(wordCount >= 300, "Page has substantial text content", () =>
      finding("thin-content", "low", "Thin content",
        `Only ${wordCount} words of visible text. Pages with very little text rarely rank for anything.`,
        "Add more useful, descriptive text content to this page (aim for 300+ words explaining what it offers)."))
  }

  const titleLower = primaryTitle.toLowerCase()
  if (!primaryTitle) {
    findings.push(finding("title-missing", "high", "Missing page title",
      "The <title> is what shows as the blue link in Google results and in browser tabs.",
      "Add a unique, descriptive <title> (30–60 characters) that says what the site is and who it's for."))
  } else if (TEMPLATE_TITLES.includes(titleLower)) {
    findings.push(finding("title-template", "high", "Page title is still the template default",
      `Your title is "${primaryTitle}", the default from a starter template. This is what people see in Google results and browser tabs.`,
      `Replace the default page title "${primaryTitle}" (in index.html or the layout metadata) with a unique, descriptive title of 30–60 characters.`,
      primaryTitle))
  } else if (primaryTitle.length < 30 || primaryTitle.length > 60) {
    findings.push(finding("title-length", "low", `Title is ${primaryTitle.length} characters`,
      "Titles between 30 and 60 characters display best in search results without being cut off.",
      `Rewrite the page title "${primaryTitle}" to be 30–60 characters, keeping the main keyword near the start.`,
      primaryTitle))
  } else {
    passed.push("Title is set and a good length")
  }

  if (titles.length > 1) {
    findings.push(finding("title-multiple", "low", `${titles.length} <title> tags found`,
      "Multiple title tags confuse search engines about which one to use.",
      "Make sure the page renders exactly one <title> tag."))
  }

  const descLower = metaDescription.toLowerCase()
  if (!metaDescription) {
    findings.push(finding("description-missing", "medium", "Missing meta description",
      "Without one, Google picks random text from the page for your search snippet.",
      "Add a meta description (120–160 characters) that summarises the page and encourages clicks."))
  } else if (TEMPLATE_DESCRIPTIONS.some(t => descLower.includes(t))) {
    findings.push(finding("description-template", "high", "Meta description is still the template default",
      `Your description is "${metaDescription}", which comes from a starter template.`,
      `Replace the default meta description "${metaDescription}" with a real 120–160 character summary of the site.`,
      metaDescription))
  } else if (metaDescription.length < 120 || metaDescription.length > 160) {
    findings.push(finding("description-length", "low", `Meta description is ${metaDescription.length} characters`,
      "120–160 characters shows fully in search results.",
      "Rewrite the meta description to be 120–160 characters."))
  } else {
    passed.push("Meta description is set and a good length")
  }

  const leakedLocal = [canonical, og.url, og.image].find(v => LOCAL_URL.test(v))
  check(!leakedLocal, "No localhost URLs in metadata", () =>
    finding("localhost-urls", "high", "Metadata points to localhost",
      "Your canonical or Open Graph tags contain a localhost address left over from development, so search engines and social previews point to a URL that doesn't exist.",
      "Replace every localhost URL in the canonical and Open Graph meta tags with the production domain (set the site URL / metadataBase from an environment variable).",
      leakedLocal))

  if (canonical && canonicalMismatch && !leakedLocal) {
    findings.push(finding("canonical-mismatch", "medium", "Canonical URL points somewhere else",
      "The canonical tag tells Google which URL is the 'real' one. It points to a different page, so this page may be dropped from results.",
      `The canonical tag on ${url} points to ${canonicalResolved}. Make each page's canonical point to its own production URL.`,
      canonical))
  } else if (canonical) {
    passed.push("Canonical URL matches the page")
  }

  check(viewport.includes("width=device-width"), "Mobile viewport is set", () =>
    finding("viewport", "medium", "Not set up for mobile",
      "Missing `width=device-width` viewport tag. Google indexes the mobile version of sites, so this hurts rankings.",
      'Add <meta name="viewport" content="width=device-width, initial-scale=1"> to the page head.'))

  check(!!lang, "Page language is declared", () =>
    finding("lang", "low", "Page language not declared",
      "The <html> tag has no `lang` attribute, which helps search engines and screen readers.",
      'Add a lang attribute to the <html> tag, e.g. <html lang="en">.'))

  if (!isEmptyShell) {
    if (h1s.length === 0) {
      findings.push(finding("h1-missing", "medium", "No H1 heading",
        "The H1 is the main headline that tells search engines what the page is about.",
        "Add exactly one <h1> heading near the top of the page that describes its main topic."))
    } else if (h1s.length > 1) {
      findings.push(finding("h1-multiple", "low", `${h1s.length} H1 headings`,
        "One clear H1 per page is best practice.",
        "Keep one <h1> per page and change the others to <h2>/<h3>."))
    } else {
      passed.push("One H1 heading")
    }
  }

  check(imagesMissingAlt === 0, "All images have alt text", () =>
    finding("img-alt", "low", `${imagesMissingAlt} image${imagesMissingAlt === 1 ? "" : "s"} missing alt text`,
      "Alt text helps images appear in Google Images and is required for accessibility.",
      "Add descriptive alt text to every <img> on the page (empty alt=\"\" only for purely decorative images)."))

  check(!!og.image, "Social preview image is set", () =>
    finding("og-image", "medium", "No social preview image",
      "When your link is shared on social media, Slack or iMessage, it shows no image and gets fewer clicks.",
      "Add an og:image (1200×630 PNG/JPG, absolute URL) plus og:title and og:description meta tags."))

  if (/lovable\.dev|gpteng/i.test(og.image) || /lovable\.dev/i.test(twitter.image)) {
    findings.push(finding("og-default", "medium", "Social preview shows the builder's default image",
      "Your link previews show the AI builder's placeholder image instead of your brand.",
      "Replace the default og:image and twitter:image with my own 1200×630 branded image.",
      og.image))
  }

  check(!!og.title && !!og.description, "Open Graph title and description are set", () =>
    finding("og-text", "low", "Missing Open Graph title or description",
      "Social platforms use these for link previews; without them they guess.",
      "Add og:title and og:description meta tags."))

  const defaultFavicon = /\/(vite|next|vercel)\.svg$/i.test(favicon)
  check(!!favicon && !defaultFavicon, "Custom favicon is set", () =>
    finding("favicon", "low", favicon ? "Favicon is the template default" : "No favicon",
      "The favicon shows in browser tabs, bookmarks and Google mobile results.",
      "Add my own favicon (and an apple-touch-icon) and remove the template default.",
      favicon))

  check(sitemapFound, "sitemap.xml found", () =>
    finding("sitemap", "medium", "No sitemap.xml",
      "A sitemap helps search engines discover all your pages, especially on new sites with few links.",
      "Generate a sitemap.xml listing all public pages, serve it at /sitemap.xml, and reference it in robots.txt."))

  check(schema.length > 0, "Structured data present", () =>
    finding("schema", "low", "No structured data",
      "Structured data (JSON-LD) can earn rich results in Google, like ratings, FAQs or your logo.",
      "Add JSON-LD structured data appropriate to this site (e.g. Organization or WebSite, plus Product/FAQ where relevant)."))

  check(isHttps, "Served over HTTPS", () =>
    finding("https", "medium", "Not served over HTTPS",
      "Google ranks HTTPS sites higher and browsers mark HTTP sites 'Not secure'.",
      "Serve the site over HTTPS and redirect all HTTP traffic to HTTPS."))

  check(mixedContent.length === 0, "No insecure (http://) images", () =>
    finding("mixed-content", "medium", "Insecure images on a secure page",
      "Some images load over http://, which browsers block or warn about.",
      "Change all image URLs to https:// (or relative paths).",
      mixedContent[0]))

  const sorted = sortFindings(findings)

  return {
    url,
    status,
    stack: detectStack(html, parsedUrl.hostname),
    summary: summarize(sorted),
    findings: sorted,
    passed,

    onPage: {
      title: {
        value: primaryTitle,
        length: primaryTitle.length,
        count: titles.length,
        all: titles
      },

      metaDescription: {
        value: metaDescription,
        length: metaDescription.length
      },

      canonical: {
        value: canonical,
        mismatch: canonicalMismatch
      },

      robots: {
        value: robotsMeta || xRobots,
        noindex
      },

      viewport: {
        value: viewport
      },

      headings: {
        h1Count: h1s.length,
        h1s,
        all: headings
      },

      content: {
        wordCount,
        emptyShell: isEmptyShell
      },

      images: {
        total: images.length,
        missingAlt: imagesMissingAlt,
        mixedContent
      },

      links: {
        internalCount: internalLinks.length,
        externalCount: externalLinks.length
      },

      openGraph: og,
      twitter,
      schema,

      security: {
        https: isHttps
      }
    }
  }
}

// True if robots.txt disallows "/" for the * user agent.
function robotsTxtBlocksAll(robotsTxt) {
  if (typeof robotsTxt !== "string") return false

  let inStarGroup = false
  let lastWasAgent = false

  for (const raw of robotsTxt.split(/\r?\n/)) {
    const line = raw.replace(/#.*/, "").trim()
    if (!line) continue
    const [key, ...rest] = line.split(":")
    const field = key.trim().toLowerCase()
    const value = rest.join(":").trim()

    if (field === "user-agent") {
      if (!lastWasAgent) inStarGroup = false
      if (value === "*") inStarGroup = true
      lastWasAgent = true
      continue
    }
    lastWasAgent = false

    if (inStarGroup && field === "disallow" && value === "/") return true
  }
  return false
}
